import { useState, useEffect } from 'react';
import { convertDriveUrl, fetchSheetCsv } from '../lib/sheets';
import manifest from '../data/portfolio.json';

const PHOTOS_CSV_URL = import.meta.env.VITE_SHEETS_PHOTOS_CSV;
const CATEGORIES_CSV_URL = import.meta.env.VITE_SHEETS_CATEGORIES_CSV;

const DEFAULT_CATEGORIES = [
  { id: 'all', label: 'All Works', kanji: '全' },
];

// Prefer the locally-bundled, pre-optimized images (generated by
// `npm run fetch:portfolio`). They're served from our own CDN and load
// instantly. Only fall back to the live Google Sheet if the manifest is empty.
const hasLocal = Array.isArray(manifest.items) && manifest.items.length > 0;

export function usePortfolioData() {
  const enabled = !hasLocal && !!(PHOTOS_CSV_URL && CATEGORIES_CSV_URL);
  const [items, setItems] = useState(hasLocal ? manifest.items : []);
  const [categories, setCategories] = useState(
    hasLocal ? manifest.categories : DEFAULT_CATEGORIES
  );
  const [loading, setLoading] = useState(enabled);

  useEffect(() => {
    if (!enabled) return;

    let cancelled = false;

    async function load() {
      try {
        const [photos, cats] = await Promise.all([
          fetchSheetCsv(PHOTOS_CSV_URL),
          fetchSheetCsv(CATEGORIES_CSV_URL),
        ]);

        if (cancelled) return;

        const parsedCategories = [
          { id: 'all', label: 'All Works', kanji: '全' },
          ...cats.map((c) => ({
            id: (c.id || c.label || '').toLowerCase().trim(),
            label: c.label || c.id || '',
            kanji: c.kanji || '',
          })),
        ];

        const parsedItems = photos
          .filter((p) => (p.image_url || p.imageurl || p.image || p.url || '').trim())
          .map((p, i) => ({
            id: i + 1,
            src: convertDriveUrl(p.image_url || p.imageurl || p.image || p.url || ''),
            category: (p.category || p.type || '').toLowerCase().trim(),
          }));

        setCategories(parsedCategories);
        setItems(parsedItems);
      } catch (err) {
        console.error('Failed to load portfolio from Google Sheets:', err);
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    load();
    return () => { cancelled = true; };
  }, []);

  return { items, categories, loading };
}
